### ISSUE TITLE
1.16.3 doesn't launch

### ISSUE THREAD

**Issue by ghost** [Arc-blroth/ProjectInception#1]
**Link to Log** (must be a link to a pastebin-like site. Logs can be found in the logs folder under your minecraft or modpack folder)
https://pastebin.com/7GTmFNeP

crash report - https://pastebin.com/xVBFvbHb

**Bug Description**
game just doesn't launch, seems that it crashed on

**Environment**
OS Linux, version 5.8.6-1
Minecraft version 1.16.3
Fabric Loader version 0.10.0+build.208

**What were you doing that may have led up to or caused the issue?**
launcher the game

**Applicable Screenshots**
none, just the loading screen

**Comment by Arc-blroth** [comment]
Hmm... I'll look into this
I have probably messed up somewhere

**Comment by Arc-blroth** [comment]
This should hopefully be fixed now - the issue was that I forgot to add an extra dependency for linux lol
Here's the updated release: https://github.com/Arc-blroth/ProjectInception/releases/tag/v1.3.1
