### ISSUE TITLE
Crash due to "Could not initialize JOGL natives!"

### ISSUE THREAD

**Issue by ghost** [Arc-blroth/ProjectInception#2]
**Link to Log** (must be a link to a pastebin-like site. Logs can be found in the logs folder under your minecraft or modpack folder)
log - https://pastebin.com/x8UgrfLG
crash report - https://pastebin.com/6nTD4mtm

**Bug Description**
launch MC, and it crashes

**Environment**
OS Linux, version 5.8.6-1
Minecraft version 1.16.3
Fabric Loader version 0.10.0+build.208

**What were you doing that may have led up to or caused the issue?**
nothing

**Clues to solving**
apparently mc fails to load native jogl - installing it externally did nothing

**Comment by Arc-blroth** [comment]
huh
sorry about all the crashes, I'll look into this some more
