### ISSUE TITLE
CEF Initialization Failed: Unexpected Termination (Exit Code 2)

### ISSUE THREAD

**Issue by ghost** [Arc-blroth/ProjectInception#6]
**Link to Log** (must be a link to a pastebin-like site. Logs can be found in the logs folder under your minecraft or modpack folder)
log - https://paste.ee/p/h9k2G
crash report - https://paste.ee/p/Hgeyj

**Bug Description**
same as usual, gets stuck on loading screen and quits with an error message; this time, it was "CEF Initialization Failed"

**Environment**
OS Linux, version 5.8.11-1
Minecraft version 1.16.3
Fabric Loader version 0.10.1+build.209
>**Mod version 1.3.2+beta.1**

**What were you doing that may have led up to or caused the issue?**
Firstly I tried to self-build yesterday the beta version - successfully build, unsuccessfully run.
Then I tried your beta version from Curseforge, resulted in same error.

**Applicable Screenshots**
none

**Comment by ghost** [comment]
it solved #2, but introduced this

**Comment by Arc-blroth** [comment]
Okay I have absolutely no idea what's crashing now, but I think it might be an os-specific issue, and thus I'm going to ask you to do a few things to try and debug this:

Run the game with [this](https://github.com/Arc-blroth/ProjectInception/releases/download/v1.3.2%2Bbeta.1/projectInception-1.3.2+debug.jar) version of the mod (or build the latest commit from this github). Once the game crashes, look in the logs folder for a file called `project-inception-taterwebz-latest.log`. If that file exists and ends with an Exception of some sort, put it in a pastebin here.

If it doesn't exist, that means that the browser process isn't launching. In `latest.log`, you should see a line that contains `Running command line:`, along with the exact command line that the mod tries to run to launch chromium. Do not send this line to me; it contains potentially sensitive info like where you've installed Minecraft. Instead, try opening a terminal and running that entire command, and see what it outputs.

Also sorry for the wall of text, but this is probably the easiest way for me to get a gist of what exactly is crashing things :)

**Comment by KirbyKid256** [comment]
So I'm seeing a consistent pattern in the log. It keeps saying "no jcef in java.library.path". I'm not sure if this helps, but that's my observation. I'm using a MacBook Air by the way.

**Comment by Arc-blroth** [comment]
Okay, gotcha. I know exactly what's going wrong now, at least with your issue, though I am not sure if it is the same issue as yuuki's

**Comment by ghost** [comment]
Sup, so it seems that my system has just badly configured Java - the debug version doesn't output any `project-inception-taterwebz-latest.log` and the command generated by it outputs:
```
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.
```
despite the fact I have such file on the system.
Sorry for stressing you for a client-side issue

**Comment by yuuki-san** [comment]
Sup, so it seems that my system has just badly configured Java - the debug version doesn't output any `project-inception-taterwebz-latest.log` and the command generated by it outputs:
```
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.
```
despite the fact I have such file on the system -_-
Sorry for stressing you for a client-side issue

**Comment by Arc-blroth** [comment]
It's okay :)
As far as I know, this message occurs whenever you run a different java/javac executable than the ones linked in /usr/bin.
I'm not sure if I can fix it, since it is caused by the particular installation of Java, but I'll see if I can at least show a warning.
